AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BuildRoleArn:
    Type: String
  AssetInsightId:
    Type: String
  ServiceName:
    Type: String
  ProjectName:
    Type: String
  FinancialIdentifier:
    Type: String
  CicdProdVpcId:
    Type: String
  CicdProdPrivateSubnets:
    Type: "List<AWS::EC2::Subnet::Id>"
  ResourceOwner:
    Type: String
  CiEnvFullName:
    Type: String
  GitHubProjectLocation:
    Type: String
  CiBuildSpecName:
    Type: String

Resources:
  CiRunnerBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: "NO_ARTIFACTS"
      Name: !Sub "a${AssetInsightId}-${ServiceName}-${ProjectName}-ciRunner-Build"
      ServiceRole: !Ref BuildRoleArn
      Environment:
        Type: "LINUX_CONTAINER"
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:2.0"
        PrivilegedMode: true
      Source:
        Auth:
          Type: OAUTH
        Location: !Ref GitHubProjectLocation
        BuildSpec: !Ref CiBuildSpecName
        Type: "GITHUB"
        ReportBuildStatus: true
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      TimeoutInMinutes: 30
      VpcConfig:
        SecurityGroupIds: [{Ref: "BuildSecurityGroup"}]
        Subnets: !Ref CicdProdPrivateSubnets
        VpcId: !Ref CicdProdVpcId
      Tags:
        - Key: "tr:application-asset-insight-id"
          Value: !Ref AssetInsightId
        - Key: "tr:financial-identifier"
          Value: !Ref FinancialIdentifier
        - Key: "tr:environment-type"
          Value: !Ref CiEnvFullName
        - Key: "tr:resource-owner"
          Value: !Ref ResourceOwner

  BuildSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group that is applied to build resources"
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: "tr:application-asset-insight-id"
          Value: !Ref AssetInsightId
        - Key: "tr:financial-identifier"
          Value: !Ref FinancialIdentifier
        - Key: "tr:environment-type"
          Value: !Ref CiEnvFullName
        - Key: "tr:resource-owner"
          Value: !Ref ResourceOwner
      VpcId: !Ref CicdProdVpcId

  SelfRule:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      Description: "Allow resources in group to talk to each other"
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      GroupId: !Ref BuildSecurityGroup
      SourceSecurityGroupId: !Ref BuildSecurityGroup

Outputs:
  BuildArn:
    Value: !GetAtt CiRunnerBuild.Arn
