template_path: templates/IACBuild.yaml

parameters:
  Environment: {{ var.QaEnvShortName }}
  ServiceName: {{ var.ServiceName }}
  ProjectName: {{ var.ProjectName }}
  BuildRoleArn: {{ var.BuildRoleArn }}
  AccountId: "{{ var.CicdProdAccountId }}"
  VpcId: {{ var.CicdProdVpcId }}
  PrivateSubnets: {{ var.CicdProdPrivateSubnets }}
  AssetInsightId: "{{ var.AssetInsightId }}"
  FinancialIdentifier: "{{ var.FinancialIdentifier }}"
  ResourceOwner: {{ var.ResourceOwner }}
  EnvironmentType: {{ var.QaEnvFullName }}
  SNSTci: {{ var.SNSTci }}

stack_tags:
  "tr:financial-identifier": "{{ var.FinancialIdentifier }}"
  "tr:application-asset-insight-id": "{{ var.AssetInsightId }}"
  "tr:environment-type": {{ var.QaEnvFullName }}
  "tr:resource-owner": {{ var.ResourceOwner }}
